apiVersion: apps/v1
kind: Deployment

metadata:
  name: wordpress-deployment

spec:
  selector:
    matchLabels:
      app: app-wordpress
  replicas: 1

  template:
    metadata:
      name: wordpress
      labels:
        app: app-wordpress

    spec:
      containers:
        - name: wordpress
          image: jojmoralespa/wordpress:v1
          env:
            - name: WORDPRESS_DB_HOST
              value: svc-mysql
            - name: WORDPRESS_DB_USER
              value: johan
            - name: WORDPRESS_DB_PASSWORD
              value: johan1234
            - name: WORDPRESS_DB_NAME
              value: wordpress_db
          ports:
            - containerPort: 80
          volumeMounts:
            - name: persistent-storage-wordpress
              mountPath: /var/www/html
      volumes:
        - name: persistent-storage-wordpress
          persistentVolumeClaim:
            claimName: pvc-wordpress