apiVersion: v1
kind: Service

metadata:
  name: svc-mysql
  labels:
    app: wordpress
    version: v1

spec:
  type: ClusterIP
  selector: 
    app: app-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306