apiVersion: v1
kind: Service

metadata:
  name: svc-wordpress
  labels:
    app: web-wordpress
    version: v1

spec:
  type: LoadBalancer
  selector:
    app: app-wordpress
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
